# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_castdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CastDialog(object):
    def setupUi(self, CastDialog):
        CastDialog.setObjectName("CastDialog")
        CastDialog.resize(677, 512)
        CastDialog.setMinimumSize(QtCore.QSize(600, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("film.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CastDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(CastDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelName = QtWidgets.QLabel(CastDialog)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout.addWidget(self.labelName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelPhoto = QtWidgets.QLabel(CastDialog)
        self.labelPhoto.setText("")
        self.labelPhoto.setObjectName("labelPhoto")
        self.horizontalLayout.addWidget(self.labelPhoto)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(CastDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.leBirth = QtWidgets.QLineEdit(CastDialog)
        self.leBirth.setObjectName("leBirth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leBirth)
        self.label_4 = QtWidgets.QLabel(CastDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.leDeath = QtWidgets.QLineEdit(CastDialog)
        self.leDeath.setObjectName("leDeath")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leDeath)
        self.label_2 = QtWidgets.QLabel(CastDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.listMovies = QtWidgets.QListWidget(CastDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listMovies.sizePolicy().hasHeightForWidth())
        self.listMovies.setSizePolicy(sizePolicy)
        self.listMovies.setObjectName("listMovies")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.listMovies)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonTrivia = QtWidgets.QPushButton(CastDialog)
        self.buttonTrivia.setObjectName("buttonTrivia")
        self.horizontalLayout_2.addWidget(self.buttonTrivia)
        self.buttonClose = QtWidgets.QPushButton(CastDialog)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout_2.addWidget(self.buttonClose)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(CastDialog)
        QtCore.QMetaObject.connectSlotsByName(CastDialog)
        CastDialog.setTabOrder(self.leBirth, self.leDeath)

    def retranslateUi(self, CastDialog):
        _translate = QtCore.QCoreApplication.translate
        CastDialog.setWindowTitle(_translate("CastDialog", "Cast Information"))
        self.labelName.setText(_translate("CastDialog", "Actor Name"))
        self.label.setText(_translate("CastDialog", "Birth"))
        self.label_4.setText(_translate("CastDialog", "Death"))
        self.label_2.setText(_translate("CastDialog", "Movies"))
        self.buttonTrivia.setText(_translate("CastDialog", "Trivia"))
        self.buttonClose.setText(_translate("CastDialog", "Close"))

