# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_moviedialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MovieDialog(object):
    def setupUi(self, MovieDialog):
        MovieDialog.setObjectName("MovieDialog")
        MovieDialog.resize(708, 563)
        MovieDialog.setMinimumSize(QtCore.QSize(550, 424))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("film.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MovieDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MovieDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(MovieDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.leDirector = QtWidgets.QLineEdit(MovieDialog)
        self.leDirector.setEnabled(True)
        self.leDirector.setReadOnly(True)
        self.leDirector.setObjectName("leDirector")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leDirector)
        self.label_2 = QtWidgets.QLabel(MovieDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.leRuntime = QtWidgets.QLineEdit(MovieDialog)
        self.leRuntime.setReadOnly(True)
        self.leRuntime.setObjectName("leRuntime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.leRuntime)
        self.label_3 = QtWidgets.QLabel(MovieDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(MovieDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.listCast = QtWidgets.QListWidget(MovieDialog)
        self.listCast.setObjectName("listCast")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.listCast)
        self.label_5 = QtWidgets.QLabel(MovieDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(MovieDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.leSearch = QtWidgets.QLineEdit(MovieDialog)
        self.leSearch.setObjectName("leSearch")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leSearch)
        self.listMovie = QtWidgets.QListWidget(MovieDialog)
        self.listMovie.setObjectName("listMovie")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.listMovie)
        self.tePlot = QtWidgets.QPlainTextEdit(MovieDialog)
        self.tePlot.setMinimumSize(QtCore.QSize(0, 0))
        self.tePlot.setMaximumSize(QtCore.QSize(16777215, 80))
        self.tePlot.setSizeIncrement(QtCore.QSize(0, 0))
        self.tePlot.setReadOnly(True)
        self.tePlot.setObjectName("tePlot")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tePlot)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonSearch = QtWidgets.QPushButton(MovieDialog)
        self.buttonSearch.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonSearch.setObjectName("buttonSearch")
        self.horizontalLayout.addWidget(self.buttonSearch)
        self.buttonExit = QtWidgets.QPushButton(MovieDialog)
        self.buttonExit.setObjectName("buttonExit")
        self.horizontalLayout.addWidget(self.buttonExit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MovieDialog)
        QtCore.QMetaObject.connectSlotsByName(MovieDialog)
        MovieDialog.setTabOrder(self.leSearch, self.leDirector)
        MovieDialog.setTabOrder(self.leDirector, self.leRuntime)
        MovieDialog.setTabOrder(self.leRuntime, self.listCast)
        MovieDialog.setTabOrder(self.listCast, self.buttonSearch)
        MovieDialog.setTabOrder(self.buttonSearch, self.buttonExit)

    def retranslateUi(self, MovieDialog):
        _translate = QtCore.QCoreApplication.translate
        MovieDialog.setWindowTitle(_translate("MovieDialog", "IMDB Browser"))
        self.label.setText(_translate("MovieDialog", "Director"))
        self.label_2.setText(_translate("MovieDialog", "Runtime"))
        self.label_3.setText(_translate("MovieDialog", "Plot"))
        self.label_4.setText(_translate("MovieDialog", "Cast"))
        self.label_5.setText(_translate("MovieDialog", "Movie"))
        self.label_6.setText(_translate("MovieDialog", "Search"))
        self.buttonSearch.setText(_translate("MovieDialog", "&Search"))
        self.buttonExit.setText(_translate("MovieDialog", "E&xit"))

